{% set name = "cpppath" %}
{% set version = "0.2.1" %}
{% set sha256 = "0629e173dc11d9fca4582fec087ccc52029a00d898573d0720bdfcf2520a6ae4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/cpppath/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - test -f ${PREFIX}/include/cpppath.h  # [unix]
    - test -f ${PREFIX}/lib/cmake/cpppath/cpppathConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\cpppath.h (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\cpppathConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/cpppath
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Simple, header only, file-path module for C++ similar to `os` in Python.'
  description: 'Simple, header only, file-path module for C++ similar to `os` in Python.'
  doc_url: https://github.com/tdegeus/cpppath
  dev_url: https://github.com/tdegeus/cpppath

extra:
  recipe-maintainers:
    - tdegeus
